# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='places_images/'),
        ),
    ]
