# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190115_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Rate'),
        ),
    ]
