# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190121_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rate',
        ),
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.ManyToManyField(to='places.Rate'),
        ),
    ]
